######################################################################
# Automatically generated by qmake (3.0) Sun Sep 18 22:20:08 2016
######################################################################

TEMPLATE = app
TARGET = digikryss
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += src/cardreader.h src/mainwindow.h
SOURCES += src/cardreader.cpp \
           src/main.cpp \
           src/mainwindow.cpp \
